/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import POJO.TraCuuKH;
import DAO.TraCuuKHDAO;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
        
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vumin
 */
public class QL_TraCuuThongTin extends javax.swing.JFrame {

    private static String makh;
    private static String string;

    /**
     * Creates new form QL_TraCuuThongTin
     */
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DefaultTableModel tblModel;
    static ArrayList<TraCuuKH> dskh = TraCuuKHDAO.getDSKH(makh);
    public QL_TraCuuThongTin() 
    {
        initComponents();
        bangKH();
    }
    
    public void bangKH(){
        tblTitle.add("MAHOADON"); tblTitle.add("MANV"); 
        tblTitle.add("TENKH"); tblTitle.add("SDT");
        tblTitle.add("SOLUONG"); tblTitle.add("THANHTIEN");tblTitle.add("TRANGTHAI");
    }
    public void laydulieuKH(ArrayList<TraCuuKH> dskq){
        tblData.removeAllElements();
        for(TraCuuKH kq : dskq){
            Vector v = new Vector();
            v.add(kq.getMahd()); v.add(kq.getManv()); 
            v.add(kq.getTenkh());v.add(kq.getSdt());
            v.add(kq.getSoluong()); v.add(kq.getThanhtien());
            v.add(kq.getTrangthai()); 
            tblData.add(v);
        }
        tbl_tracuukh.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_tracuu = new javax.swing.JButton();
        txt_makh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tracuukh = new javax.swing.JTable();
        btn_chuyensangmuave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Khách Hàng");

        btn_tracuu.setText("Tra Cứu");
        btn_tracuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tracuuActionPerformed(evt);
            }
        });

        tbl_tracuukh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_tracuukh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tracuukhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tracuukh);

        btn_chuyensangmuave.setText("Mua vé");
        btn_chuyensangmuave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chuyensangmuaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(txt_makh)
                .addGap(18, 18, 18)
                .addComponent(btn_tracuu)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_chuyensangmuave)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tracuu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_chuyensangmuave)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tracuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tracuuActionPerformed
        // TODO add your handling code here:
        ArrayList<TraCuuKH> makh=TraCuuKHDAO.getDSKH(txt_makh.getText());
        tblData.removeAllElements();
        for(TraCuuKH kq : makh){
            Vector v = new Vector();
            v.add(kq.getMahd()); v.add(kq.getManv()); 
            v.add(kq.getTenkh());v.add(kq.getSdt());
            v.add(kq.getSoluong()); v.add(kq.getThanhtien());
            v.add(kq.getTrangthai()); 
            tblData.add(v);
        }
        tbl_tracuukh.setModel(new DefaultTableModel(tblData, tblTitle));
    }//GEN-LAST:event_btn_tracuuActionPerformed

    private void btn_chuyensangmuaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chuyensangmuaveActionPerformed
        // TODO add your handling code here:
        close();
        QL_MuaVe tk = new QL_MuaVe();
        tk.setVisible(true);
    }//GEN-LAST:event_btn_chuyensangmuaveActionPerformed

    private void tbl_tracuukhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tracuukhMouseClicked
        // TODO add your handling code here:
        /*
        String mahv = tbl_KetQua.getValueAt(tbl_KetQua.getSelectedRow(), 0).toString();
        String mamon = tbl_KetQua.getValueAt(tbl_KetQua.getSelectedRow(), 1).toString();
        String lanthi = tbl_KetQua.getValueAt(tbl_KetQua.getSelectedRow(), 2).toString();
        String diem = tbl_KetQua.getValueAt(tbl_KetQua.getSelectedRow(), 3).toString();
        
        txt_MaHV.setText(mahv);
        txt_MaMon.setText(mamon);
        txt_LanThi.setText(lanthi);
        txt_Diem.setText(diem);
        setTenHVVaMaMon();
        */
    }//GEN-LAST:event_tbl_tracuukhMouseClicked
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_TraCuuThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_TraCuuThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_TraCuuThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_TraCuuThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_TraCuuThongTin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chuyensangmuave;
    private javax.swing.JButton btn_tracuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_tracuukh;
    private javax.swing.JTextField txt_makh;
    // End of variables declaration//GEN-END:variables
}
